[hyperparameters]
p_val = 2
margin = 2
batch_size = 45
embedding_size = 128
triplet_swapping = true

[training]
seed = 4242
epochs = 15_000
gpu_number = 0
print_iter = 100
val_iter = 500
name = "default"
gan_config = "/home/struan/Development/Doctorate/one_to_many_gan/implementation/config.toml"
resume_checkpoint = "" # Leave empty for no resuming

[training.pre_training]
pre_trained = true
frozen = true
epoch_unfreeze = 2000 # Number of epochs between layer unfreezes
defrost = 0 # When to start layer unfreezing
# TODO try permafrost 5 when I have all my hyperparameters tuned and I train for longer
permafrost = 4 # Number of layers to unfreeze before leaving frozen, 0 to unfreeze all 
refreeze = false # Refreeze previous layer after unfreezing one before


[training.shoemark_augmentation]
max_translation = [64, 32]
max_rotation = 45
max_scale = 0.25
flip = true
    
[training.shoeprint_augmentation]
max_translation = [32, 16]
max_rotation = 22
max_scale = 0.125
flip = true

[data]
shoeprint_val_dir = "~/Development/Doctorate/siamese/data/Shoeprints/val/"
shoemark_val_dir = "~/Development/Doctorate/siamese/data/Shoemarks/val/"
wvu_data_dir = "~/Development/Doctorate/siamese/data/Testing/WVU2019/"
fid_data_dir = "~/Development/Doctorate/siamese/data/Testing/FID-300/Shoeprints/"
image_size = [512, 256]


[data.streaming]
floor_image_data_dir = "~/Development/Doctorate/siamese/data/flooring/"
shoeprint_data_dir = "~/Development/Doctorate/siamese/data/Streaming/Shoeprints/"
shoemark_data_dir = "~/Development/Doctorate/siamese/data/Streaming/Shoemarks/"
min_floor_roi_height = 512
synthetic_ratio = 0.5


